### ISSUE TITLE
Version 2.0.0: defined NODE_PATH will cause tests to be undetected or crashing on import.

### ISSUE THREAD

**Issue by sebastiaanviaene** [hbenl/vscode-mocha-test-adapter#54]
I'm having a problem since the 2.0.0 update.

In my tsconfig.json I have this setting: 
````
"paths": {
      "*": ["./src/*", "./tests/*"]
    }
````
Which enables me to use absolute imports where src & test is the prefix. In my mocha settings (settings.json) I have two options to include these paths into the environment.

1:

````
"mochaExplorer.env": { "NODE_PATH": "./src:./tests" },
````

With the old version this works perfectly. However since the update it crashes during the loading of the tests and says it cannot find my absolute imported modules.

2:

````
"mochaExplorer.require": ["tsconfig-paths/register"],
````

The package called "tsconfig-paths" enables you to register these NODE_PATH directly from your tsconfig.json. This also works on the previous version of the mocha test adapter. However in the new version it doesn't do anything. When I try to load the tests it doesn't even show an error. It just seems like there are no tests.

Do you guys have an idea why this is happening?

**Comment by hbenl** [comment]
The first option stopped working because the adapter now sets environment variables in the worker script whereas before they were set when the child process (that runs the worker script) is started.
As it turns out, setting `NODE_PATH` in the worker script is simply too late - it needs to be already set when node is started, not afterwards.
I have just fixed this in version 2.0.1, tell me if this works for you.

For the second option I tried 2 variants:
1. run the typescript files directly using `ts-node`:
```json
"mochaExplorer.files": "tests/**/*.ts",
"mochaExplorer.require": ["ts-node/register", "tsconfig-paths/register"]
```
2. compile the typescript files to javascript and run those:
```json
"mochaExplorer.files": "tests/**/*.js",
"mochaExplorer.require": ["tsconfig-paths/register"]
```
Both variants worked for me, so there must be something specific to your project that triggers this bug.
I'd be very grateful if you could set up an example project in which this option doesn't work so I can fix it for everyone.

**Comment by sebastiaanviaene** [comment]
I am also using ts-node currently. I tried both the NODE_PATH way and the register way on the new version and they still won't work + don't show an error message. Here's my settings.json

````
{
  "mochaExplorer.require": ["ts-node/register", "tsconfig-paths/register"],
  "mochaExplorer.env": { "NODE_ENV": "test" },
  "mochaExplorer.timeout": 99999,
  "mochaExplorer.files": "tests/**/*.test.ts",
  "mochaExplorer.exit": true,
  "mochaExplorer.pruneFiles": true,
  "mochaExplorer.logpanel": true,
  "mochaExplorer.ui": "tdd"
}
````

OR 

````
{
  "mochaExplorer.require": ["ts-node/register",],
  "mochaExplorer.env": { "NODE_ENV": "test", "NODE_PATH": "./src:./tests" },
  "mochaExplorer.timeout": 99999,
  "mochaExplorer.files": "tests/**/*.test.ts",
  "mochaExplorer.exit": true,
  "mochaExplorer.pruneFiles": true,
  "mochaExplorer.logpanel": true,
  "mochaExplorer.ui": "tdd"
}
````

They both don't work, even on 2.0.1. Sometimes (at random it seems) when I reload i get this error.
[https://i.imgur.com/ypS2MzC.png](url)

**Comment by hbenl** [comment]
I did some more experiments but I am still unable to reproduce this, please attach the output from the diagnostic log.
Also, you could try setting `mochaExplorer.exit` to 'false' to see if it at least shows an error message when it fails loading the tests.

**Comment by sebastiaanviaene** [comment]
Actually using ``"mochaExplorer.exit": false`` fixes the whole problem. My tests are now detected without problem.

**Comment by sebastiaanviaene** [comment]
Logs with ``"mochaExplorer.exit": true``

````
[2019-06-13 17:09:03.371] [INFO] Loading test files of /Users/user/Documents/projects/project
[2019-06-13 17:09:03.371] [DEBUG] Using working directory: /Users/user/Documents/projects/project
[2019-06-13 17:09:03.790] [DEBUG] Using Mocha options: {"ui":"tdd","timeout":99999,"retries":0,"requires":["ts-node/register","tsconfig-paths/register"],"exit":true}
[2019-06-13 17:09:03.801] [DEBUG] Using nodePath: /Users/user/.nvm/versions/node/v8.12.0/bin/node
[2019-06-13 17:09:03.801] [DEBUG] Using environment variables from config: {"NODE_ENV":"test"}
[2019-06-13 17:09:03.801] [DEBUG] Looking for test files ["tests/**/*.test.ts"] in /Users/user/Documents/projects/project
[2019-06-13 17:09:03.875] [DEBUG] Found test files ["/Users/user/Documents/projects/project/tests/integration/integration.test.ts","/Users/user/Documents/projects/project/tests/unit/unit.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/family.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/school.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/kid.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/user.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/pro.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/admin.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/group.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/simple.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/teacher.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/school.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/user.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/middleware.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/authentication.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/translation.test.ts"]
[2019-06-13 17:09:03.946] [INFO] Worker: Using the mocha package at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.0.1/node_modules/mocha
[2019-06-13 17:09:03.998] [INFO] Worker: Patching Mocha
[2019-06-13 17:09:03.998] [INFO] Worker: Trying require('ts-node/register')
[2019-06-13 17:09:04.268] [INFO] Worker: Trying require('tsconfig-paths/register')
[2019-06-13 17:09:04.283] [INFO] Worker: Loading files
[2019-06-13 17:09:04.284] [INFO] Worker: Patching suite
[2019-06-13 17:09:04.284] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:04.284] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:04.284] [INFO] Worker: Patching test
[2019-06-13 17:09:04.284] [INFO] Worker: Patching test.only
[2019-06-13 17:09:04.284] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:04.284] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.825] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.825] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.825] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.825] [INFO] Worker: Patching test
[2019-06-13 17:09:05.825] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.825] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.825] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.931] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.931] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.931] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.931] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.932] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.932] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.932] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test
[2019-06-13 17:09:05.932] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Patching suite.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.only
[2019-06-13 17:09:05.938] [INFO] Worker: Patching test.skip
[2019-06-13 17:09:05.938] [INFO] Worker: Copying test.retries
[2019-06-13 17:09:05.938] [INFO] Worker: Converting tests and suites
[2019-06-13 17:09:05.941] [INFO] 

  0 passing (2ms)


[2019-06-13 17:09:05.956] [INFO] Worker finished with code 0 and signal null

````


Logs with ``"mochaExplorer.exit": false``

````
[2019-06-13 17:11:32.010] [INFO] Loading test files of /Users/user/Documents/projects/project
[2019-06-13 17:11:32.011] [DEBUG] Using working directory: /Users/user/Documents/projects/project
[2019-06-13 17:11:32.283] [DEBUG] Using Mocha options: {"ui":"tdd","timeout":99999,"retries":0,"requires":["ts-node/register","tsconfig-paths/register"],"exit":false}
[2019-06-13 17:11:32.291] [DEBUG] Using nodePath: /Users/user/.nvm/versions/node/v8.12.0/bin/node
[2019-06-13 17:11:32.291] [DEBUG] Using environment variables from config: {"NODE_ENV":"test"}
[2019-06-13 17:11:32.291] [DEBUG] Looking for test files ["tests/**/*.test.ts"] in /Users/user/Documents/projects/project
[2019-06-13 17:11:32.354] [DEBUG] Found test files ["/Users/user/Documents/projects/project/tests/unit/unit.test.ts","/Users/user/Documents/projects/project/tests/integration/integration.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/family.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/school.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/kid.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/user.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/pro.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/admin.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/group.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/simple.test.ts","/Users/user/Documents/projects/project/tests/integration/parts/teacher.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/school.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/user.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/middleware.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/authentication.test.ts","/Users/user/Documents/projects/project/tests/unit/parts/translation.test.ts"]
[2019-06-13 17:11:32.563] [INFO] Worker: Using the mocha package at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.0.1/node_modules/mocha
[2019-06-13 17:11:32.625] [INFO] Worker: Patching Mocha
[2019-06-13 17:11:32.625] [INFO] Worker: Trying require('ts-node/register')
[2019-06-13 17:11:32.906] [INFO] Worker: Trying require('tsconfig-paths/register')
[2019-06-13 17:11:32.933] [INFO] Worker: Loading files
[2019-06-13 17:11:32.935] [INFO] Worker: Patching suite
[2019-06-13 17:11:32.935] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:32.935] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:32.935] [INFO] Worker: Patching test
[2019-06-13 17:11:32.935] [INFO] Worker: Patching test.only
[2019-06-13 17:11:32.935] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:32.935] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:34.359] [INFO] Worker: Patching suite
[2019-06-13 17:11:34.359] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:34.359] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:34.359] [INFO] Worker: Patching test
[2019-06-13 17:11:34.359] [INFO] Worker: Patching test.only
[2019-06-13 17:11:34.359] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:34.359] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.527] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.527] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.527] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.527] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.528] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.528] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.528] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.528] [INFO] Worker: Patching test
[2019-06-13 17:11:36.528] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.528] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.528] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.529] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.529] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Patching suite.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.only
[2019-06-13 17:11:36.530] [INFO] Worker: Patching test.skip
[2019-06-13 17:11:36.530] [INFO] Worker: Copying test.retries
[2019-06-13 17:11:36.533] [INFO] 

[2019-06-13 17:11:36.534] [INFO] 

[2019-06-13 17:11:36.534] [INFO]   0 passing (2ms)

[2019-06-13 17:11:36.534] [INFO] 

[2019-06-13 17:11:36.535] [INFO] Worker: Converting tests and suites
[2019-06-13 17:11:36.540] [INFO] Received tests from worker
[2019-06-13 17:11:36.551] [INFO] Worker finished with code 0 and signal null


````

**Comment by hbenl** [comment]
So it seems that the last messages that the child process (which runs mocha) sends to Test Explorer are getting lost with `"mochaExplorer.exit": true` - apparently the child process is exiting too fast (when the messages are still in its output buffer).
I'll fix this soon.

**Comment by hbenl** [comment]
In version 2.1.0, the `mochaExplorer.exit` option should be fixed, please tell me if it works for you.
Furthermore, if you're feeling adventurous, you could try the new support for [running the tests from transpiled sources](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter#user-content-using-transpilers-(typescript%2C-babel%2C-etc.)) by using `"mochaExplorer.require": "source-map-support/register"`.

**Comment by sebastiaanviaene** [comment]
Yes it works perfectly with the exit option enabled now. Thanks!
